### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by DannyParker0001** [korewaChino/libplaymc#1]
Rust is an elegant, blazing fast, memory safe language. C++ is what old people use, if you want _ACTUAL_ contributers you should switch to rust, its what everyone uses now.

**Comment by korewaChino** [comment]
> Rust is an elegant, blazing fast, memory safe language. C++ is what old people use, if you want _ACTUAL_ contributers you should switch to rust, its what everyone uses now.

https://github.com/korewaChino/libpolymc

**Comment by DannyParker0001** [comment]
LOL
